# Generated by Django 4.0.4 on 2022-05-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_alter_follower_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-id'], 'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
