# Generated by Django 4.0.4 on 2022-05-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_myuser_biography_myuser_birthday_myuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='technology',
            field=models.ManyToManyField(related_name='users', to='custom_user.technology'),
        ),
    ]
